# Generated by Django 5.0 on 2024-01-03 18:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0019_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='avt',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='avt'),
        ),
    ]
